[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Power of Behavioral Interviewing: Techniques for Assessing Candidates' Past Behavior and Predicting Future Performance"
